version: "3.8"

services:
  redis:
    image: redis:7.4.2-bookworm
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=your_secure_password
    command: redis-server --requirepass $$REDIS_PASSWORD
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-redis-sample
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=your_secure_password
      - REDIS_DB=0
      - HTTP_PORT=3000
      - LOG_LEVEL=debug
      - CACHE_EXPIRATION_TIME=120
    depends_on:
      redis:
        condition: service_healthy
