apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.secret.REDIS_PASSWORD | quote }} 