basePath: /
definitions:
  models.UserProfile:
    properties:
      address:
        type: string
      city:
        type: string
      email:
        type: string
      name:
        type: string
      phone:
        type: string
      state:
        type: string
      zip:
        type: string
    type: object
info:
  contact: {}
  description: This is a sample API using Go, Gin, and Redis
  title: Go Redis Sample API
  version: "1.0"
paths:
  /user-profile/{user-id}:
    delete:
      description: Delete a user profile from Redis
      parameters:
      - description: User ID
        in: path
        name: user-id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
          schema:
            type: object
      summary: Delete a user profile
      tags:
      - user-profile
    get:
      description: Get a user profile from Redis
      parameters:
      - description: User ID
        in: path
        name: user-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserProfile'
        "404":
          description: Not Found
          schema:
            type: object
      summary: Get a user profile
      tags:
      - user-profile
    post:
      consumes:
      - application/json
      description: Create a user profile in Redis
      parameters:
      - description: User ID
        in: path
        name: user-id
        required: true
        type: string
      - description: User Profile
        in: body
        name: userProfile
        required: true
        schema:
          $ref: '#/definitions/models.UserProfile'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.UserProfile'
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Create a user profile
      tags:
      - user-profile
    put:
      consumes:
      - application/json
      description: Update a user profile in Redis
      parameters:
      - description: User ID
        in: path
        name: user-id
        required: true
        type: string
      - description: User Profile
        in: body
        name: userProfile
        required: true
        schema:
          $ref: '#/definitions/models.UserProfile'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserProfile'
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Update a user profile
      tags:
      - user-profile
swagger: "2.0"
